[build-system]
requires = [
   'setuptools-git-versioning', 
   'pip>=19.3',
   'setuptools>=57.1.0',
   'wheel>=0.36.2',
   'build>=0.5.1',
   'cmake >= 3.20.5',
   ]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["pp*"]
build-verbosity = 1

[tool.cibuildwheel.linux]
build-frontend = "build"
manylinux-x86_64-image = "quay.io/pypa/manylinux_2_24_x86_64:latest"
manylinux-aarch64-image = "quay.io/pypa/manylinux_2_24_aarch64:latest"
before-all = [ 
   "git config --global --add safe.directory /project", 
   "git status", 
    ]
before-build = [ 
    "python -m pip install ninja", 
]

[tool.cibuildwheel.macos]
build-frontend = "build"
before-build = [ 
    "python -m pip install ninja", 
]
[tool.cibuildwheel.windows]
build-frontend = "build"
before-build = [ 
    "python -m pip install ninja", 
]
