name: Pyright

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  workflow_call:
  
jobs: 
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.9'
      - name: Get Python Version
        id: python-version
        run: |
          set -eux
          python --version > python_version.txt
          cat python_version.txt
      - name: Pip-Tools 
        run: |
          python -m pip install pip-tools 
          pip-compile dev-requirement.in
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('python_version.txt') }}-${{ hashFiles('dev-requirement.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('python_version.txt') }}-${{ hashFiles('dev-requirement.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('python_version.txt') }}
      - name: Update
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip setuptools wheel build
      - name: Install Dependencies
        shell: bash
        run: |
          set -eux
          pip-sync dev-requirement.txt
          
      - uses: jordemort/action-pyright@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          filter_mode: file
          reporter: github-pr-review
          lib: true
